name: Build and Deploy Server Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - "server/**" # Monitor changes in the server folder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: test-fullstack-server:latest
