name: Build and Push Client Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - "client/**" # Monitor changes in the client folder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Publish Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:client"
          push: true
          tags: joebanana7/test-fullstack-client:latest
