name: Build and Push Seed Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Publish Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:server"
          file: "{context}/Dockerfile.seed"
          push: true
          tags: joebanana7/test-fullstack-seed:latest
