name: Deploy Server Image to Azure App Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "test-fullstack-server"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_SERVER_PUBLISH_PROFILE }}
          images: "index.docker.io/${{ vars.SERVER_IMAGE }}:latest"
