name: Deploy Nginx Image to Azure App Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "test-fullstack"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_NGINX_PUBLISH_PROFILE }}
          images: "index.docker.io/${{ vars.NGINX_IMAGE }}:latest"
